### PR TITLE
Update awsCreateAccount.py

### PR DESCRIPTION
**Pull request by kjordanCC**

### CODE REVIEW

**Comment by gcasilva** [comment]
@kjordanCC On further testing I see the behavior below that might need code update or documentation update:
If the AWS Account is already registered in CloudCheckr than the function is just skipping registration, but then the issue is that the AWS IAM Role Arn being referenced in the CloudChecker is not updated, so it would be still referencing the previous Role ARN which would not exist anymore.
Is there a way to update this programatically? If not I think the best solution would be to add this information in the Troubleshooting section of the documentation, saying that if the customer is redeploying the Cfn template in an account that was previously registered they need to update the AWS IAM Role ARN with the new updated one.

Cursor_and_CloudCheckr

**Comment by kkvinjam** [comment]
@kjordanCC please add a default value to the variable `pEnvironment`. Alternatively, [update the .taskcat.yml ](https://github.com/aws-ia/cfn-abi-spotbynetapp-cloudcheckr/blob/3c9e2d4de24c325dde6885a00a87b5ae3b90b499/.taskcat.yml#L19)with the value to be tested.

**Review by gcasilva — APPROVED** [review]

**Pull request merged**
